= Void Wizard
//:numbered:
//:sectids!:
:toc:
:toc-placement!:
:toc-title: pass:[<h2>Table of Contents</h2>]
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

A set of scripts that automate the installation and setup process of Void Linux
with LVM on LUKS full disk encryption.

toc::[]

== Introduction

Void Wizard is a set of scripts that automate the installation and setup process
of Void Linux with LVM on LUKS full disk encryption. The goal is to get you from
an installation medium to a fully working system using
https://github.com/riverwm/river[river] -- a dynamic Wayland compositor -- along
with all your favorite programs.

This document will explain the inner workings of everything in great detail, but
here is the short overview below.

* `+systemwide_config_files/+` -- The name says it all. The structure of this
directory mimics the `+/+` (root) directory. Those files will be placed
correctly by `+vlss+`.
* `+packages.csv+` -- A list of the necessary packages. It follows a specific
format as it accommodates for packages to be installed from different sources
and at different stages.
* `+pis+` -- _Package Install Script_ takes as an input `+packages.csv+` and
(optionally) installation stage and installs either all packages from the file
or only the ones pertaining to a particular installation stage.
* `+vlss+` -- _Void Linux Setup Script_ calls `+pis+` to install the required
packages and configures various aspects of the system to get it up and running
for you. It also applies my https://github.com/vladimir-grbic/dotfiles[dotfiles]
using https://www.chezmoi.io/[chezmoi].
* `+vlis+` (work in progress) -- _Void Linux Install Script_ installs the base
system with full disk encryption by mainly performing
https://docs.voidlinux.org/installation/guides/fde.html[these steps]. Then, it
calls `+vlss+` to finish the job.

Recognize that any of these scripts can be used separately to perform their
well-defined tasks with little to no modification.

[NOTE]
====
While these scripts will automate most if not all of the installation, you
are still responsible and expected to account for a few important parameters
such as a different microcode package (if you do not have Intel's CPU) or
configuration of `+doas+` file. Please, read this document in it's entirety and
reference the code to understand the full implications.
====

Before we dive in more detail, keep in mind that you are encouraged to
replace some of the tools/packages I use, but keep in mind that you might have
to modify some instructions in `+vlss` or even `+vlis+`. For example, if you
want to install and use qutebrowser instead of Firefox that will just require
you accurately update `+packages.csv+`, while if you want to use `PulseAudio`
instead of `PipeWire` you will certainly have to modify `+vlss+` as well.

Don't be discouraged to change things to your needs especially since I tried to
be extremely verbose and comment the doings of each logical segment in the
scripts.

== Systemwide Configuration Files

== The List of Packages

== Package Install Script

== Void Linux Setup Script

== Void Linux Install Script
